/* ═══════════════════════════════════════════════════════════
   Diamond Perfume — Demo Products
   منتجات نموذجية فاخرة — استبدلها بمنتجاتك الحقيقية
   ═══════════════════════════════════════════════════════════ */
window.DP = window.DP || {};

DP.DATA = {
  CATEGORIES: [
    {
      id: 'women',
      ar: 'عطور نسائية',
      en: 'For Her',
      descAr: 'أنوثة تُروى كحكاية عطرية',
      descEn: 'Femininity told as a fragrant tale',
      image: 'assets/images/rose-verdun.jpg',
    },
    {
      id: 'men',
      ar: 'عطور رجالية',
      en: 'For Him',
      descAr: 'حضورٌ لا يُنسى',
      descEn: 'A presence never forgotten',
      image: 'assets/images/diamond-noir.jpg',
    },
    {
      id: 'oriental',
      ar: 'عود وشرقيات',
      en: 'Oud & Oriental',
      descAr: 'أصالة الشرق بلمسة ملكية',
      descEn: 'Eastern heritage with a royal touch',
      image: 'assets/images/royal-oud.jpg',
    },
    {
      id: 'niche',
      ar: 'نيش وفاخرة',
      en: 'Niche & Exclusive',
      descAr: 'توقيع عطري لا يتكرر',
      descEn: 'A scent signature like no other',
      image: 'assets/images/sapphire-nuit.jpg',
    },
  ],

  /* كل عطر متوفّر بحجمين: 50 ml و 100 ml — والحجم الأخير في القائمة هو المعروض افتراضياً
     عدّل أي سعر مباشرة من sizes */
  PRODUCTS: [
    {
      id: 'royal-oud',
      cat: 'oriental',
      gender: { ar: 'للجنسين', en: 'Unisex' },
      nameAr: 'عود رويال',
      nameEn: 'Royal Oud',
      notesAr: 'عود هندي، زعفران، عنبر رمادي',
      notesEn: 'Indian oud, saffron, grey amber',
      descAr: 'افتتاحية من الزعفران الذهبي تذوب في قلب من العود الهندي الفاخر، لتستقر على عنبرٍ دافئ يرافقك طوال اليوم.',
      descEn: 'A golden saffron opening melting into precious Indian oud, resting on warm amber that lasts all day.',
      sizes: [
        { label: '50 ml', price: 39 },
        { label: '100 ml', price: 65 },
      ],
      image: 'assets/images/royal-oud.jpg',
    },
    {
      id: 'diamond-noir',
      cat: 'men',
      gender: { ar: 'رجالي', en: 'For Him' },
      nameAr: 'دياموند نوار',
      nameEn: 'Diamond Noir',
      notesAr: 'برغموت، جلد، فيتيفر مدخّن',
      notesEn: 'Bergamot, leather, smoked vetiver',
      descAr: 'عطر الليل والحضور الطاغي؛ برغموت حاد يعانق الجلد الفاخر ودخان الفيتيفر الغامض.',
      descEn: 'The scent of night and command; sharp bergamot embracing fine leather and mysterious smoked vetiver.',
      sizes: [
        { label: '50 ml', price: 33 },
        { label: '100 ml', price: 55 },
      ],
      image: 'assets/images/diamond-noir.jpg',
    },
    {
      id: 'rose-verdun',
      cat: 'women',
      gender: { ar: 'نسائي', en: 'For Her' },
      nameAr: 'روز فردان',
      nameEn: 'Rose Verdun',
      notesAr: 'ورد دمشقي، فانيليا، مسك أبيض',
      notesEn: 'Damask rose, vanilla, white musk',
      descAr: 'وردة دمشقية قطفت عند الفجر، تتوسطها حلاوة الفانيليا ونقاء المسك الأبيض.',
      descEn: 'A Damask rose picked at dawn, wrapped in vanilla sweetness and pure white musk.',
      sizes: [
        { label: '50 ml', price: 29 },
        { label: '100 ml', price: 48 },
      ],
      image: 'assets/images/rose-verdun.jpg',
    },
    {
      id: 'sultan-amber',
      cat: 'oriental',
      gender: { ar: 'للجنسين', en: 'Unisex' },
      nameAr: 'عنبر سلطان',
      nameEn: 'Sultan Amber',
      notesAr: 'عنبر، باتشولي، خشب الصندل',
      notesEn: 'Amber, patchouli, sandalwood',
      descAr: 'تركيبة سلطانية دافئة تجمع العنبر الملكي مع عمق الباتشولي ونعومة الصندل.',
      descEn: 'A warm royal composition of amber, deep patchouli and silky sandalwood.',
      sizes: [
        { label: '50 ml', price: 35 },
        { label: '100 ml', price: 58 },
      ],
      image: 'assets/images/sultan-amber.jpg',
    },
    {
      id: 'pure-musk',
      cat: 'oriental',
      gender: { ar: 'للجنسين', en: 'Unisex' },
      nameAr: 'مسك الطهارة',
      nameEn: 'Pure Musk',
      notesAr: 'مسك أبيض، زهر القطن، ياسمين',
      notesEn: 'White musk, cotton flower, jasmine',
      descAr: 'نقاء الطهارة في زجاجة؛ مسك أبيض ناعم يعانق زهرة القطن ولمسة ياسمين.',
      descEn: 'Purity in a bottle; soft white musk embracing cotton flower with a touch of jasmine.',
      sizes: [
        { label: '50 ml', price: 22 },
        { label: '100 ml', price: 37 },
      ],
      image: 'assets/images/pure-musk.jpg',
    },
    {
      id: 'sapphire-nuit',
      cat: 'niche',
      gender: { ar: 'رجالي', en: 'For Him' },
      nameAr: 'سفير الليل',
      nameEn: 'Sapphire Nuit',
      notesAr: 'لافندر، حبوب التونكا، خشب الأرز',
      notesEn: 'Lavender, tonka bean, cedarwood',
      descAr: 'ليلٌ أزرق عميق؛ لافندر هادئ يتلألأ فوق تونكا كريمية وقاعدة من أرز الأطلس.',
      descEn: 'A deep blue night; calm lavender sparkling over creamy tonka and Atlas cedar.',
      sizes: [
        { label: '50 ml', price: 44 },
        { label: '100 ml', price: 74 },
      ],
      image: 'assets/images/sapphire-nuit.jpg',
    },
    {
      id: 'vanilla-royale',
      cat: 'women',
      gender: { ar: 'نسائي', en: 'For Her' },
      nameAr: 'فانيليا رويال',
      nameEn: 'Vanilla Royale',
      notesAr: 'فانيليا مدغشقر، كراميل، تونكا',
      notesEn: 'Madagascar vanilla, caramel, tonka',
      descAr: 'حلوى ملكية لا تُقاوم؛ فانيليا مدغشقرية كريمية مع خيوط الكراميل الذهبية.',
      descEn: 'An irresistible royal gourmand; creamy Madagascar vanilla laced with golden caramel.',
      sizes: [
        { label: '50 ml', price: 37 },
        { label: '100 ml', price: 62 },
      ],
      image: 'assets/images/vanilla-royale.jpg',
    },
    {
      id: 'saffron-leather',
      cat: 'niche',
      gender: { ar: 'للجنسين', en: 'Unisex' },
      nameAr: 'جلد الزعفران',
      nameEn: 'Saffron Leather',
      notesAr: 'زعفران، جلد إيطالي، تبغ',
      notesEn: 'Saffron, Italian leather, tobacco',
      descAr: 'جرأة الزعفران وفخامة الجلد الإيطالي في عناقٍ دافئ مع أوراق التبغ المعتّقة.',
      descEn: 'Bold saffron and luxurious Italian leather warmed by aged tobacco leaves.',
      sizes: [
        { label: '50 ml', price: 53 },
        { label: '100 ml', price: 88 },
      ],
      image: 'assets/images/saffron-leather.jpg',
    },
    {
      id: 'desert-emerald',
      cat: 'niche',
      gender: { ar: 'للجنسين', en: 'Unisex' },
      nameAr: 'زمرّد الصحراء',
      nameEn: 'Desert Emerald',
      notesAr: 'برغموت، هيل، فيتيفر أخضر',
      notesEn: 'Bergamot, cardamom, green vetiver',
      descAr: 'نسيم أخضر يعبر الصحراء؛ هيل منعش وبرغموت مشرق فوق فيتيفر أخضر نابض.',
      descEn: 'A green breeze crossing the desert; fresh cardamom and bright bergamot over vivid vetiver.',
      sizes: [
        { label: '50 ml', price: 47 },
        { label: '100 ml', price: 79 },
      ],
      image: 'assets/images/desert-emerald.jpg',
    },
    {
      id: 'cambodian-oud',
      cat: 'oriental',
      gender: { ar: 'للجنسين', en: 'Unisex' },
      nameAr: 'دهن عود كمبودي معتّق',
      nameEn: 'Aged Cambodian Oud Oil',
      notesAr: 'عود كمبودي نقي معتّق ١٢ سنة',
      notesEn: 'Pure 12-year-aged Cambodian oud',
      descAr: 'دهن عود كمبودي نقي معتّق اثنتي عشرة سنة؛ قطرة واحدة تكفي لحضورٍ يسبق اسمك.',
      descEn: 'Pure Cambodian oud oil aged twelve years; one drop precedes your name.',
      sizes: [
        { label: '50 ml', price: 72 },
        { label: '100 ml', price: 120 },
      ],
      image: 'assets/images/cambodian-oud.jpg',
    },
    {
      id: 'diamond-bakhoor',
      cat: 'oriental',
      gender: { ar: 'للبيت', en: 'For Home' },
      nameAr: 'بخور الماس الفاخر',
      nameEn: 'Diamond Bakhoor',
      notesAr: 'عود معطر، مسك، خشب الصندل',
      notesEn: 'Scented oud chips, musk, sandalwood',
      descAr: 'بخور فاخر يملأ المجلس بعبق الضيافة العربية الأصيلة.',
      descEn: 'Luxurious bakhoor that fills your majlis with authentic Arabian hospitality.',
      sizes: [
        { label: '50 ml', price: 21 },
        { label: '100 ml', price: 35 },
      ],
      image: 'assets/images/diamond-bakhoor.jpg',
    },
    {
      id: 'or-eternel',
      cat: 'women',
      gender: { ar: 'نسائي', en: 'For Her' },
      nameAr: 'أور إتيرنيل',
      nameEn: 'Or Éternel',
      notesAr: 'ياسمين، زهر البرتقال، مسك ذهبي',
      notesEn: 'Jasmine, orange blossom, golden musk',
      descAr: 'ذهبٌ سائل يفيض أنوثة؛ ياسمين ليلي يتشابك مع زهر البرتقال ومسكٍ ذهبي دافئ.',
      descEn: 'Liquid gold overflowing with femininity; night jasmine entwined with orange blossom and warm golden musk.',
      sizes: [
        { label: '50 ml', price: 34 },
        { label: '100 ml', price: 57 },
      ],
      image: 'assets/images/or-eternel.jpg',
    },
  ],

  CAT_LABEL: {
    women: { ar: 'نسائية', en: 'Women' },
    men: { ar: 'رجالية', en: 'Men' },
    oriental: { ar: 'عود وشرقيات', en: 'Oud & Oriental' },
    niche: { ar: 'نيش', en: 'Niche' },
  },

  /* ═══════════════════════════════════════════════════════
     مناطق التوصيل — المدينة / القضاء ثم المناطق التابعة له
     Delivery zones — city / district then its areas
     ═══════════════════════════════════════════════════════ */
  CITIES: [
    {
      id: 'beirut',
      ar: 'بيروت',
      en: 'Beirut',
      areas: [
        { ar: 'فردان', en: 'Verdun' },
        { ar: 'الحمرا', en: 'Hamra' },
        { ar: 'رأس بيروت', en: 'Ras Beirut' },
        { ar: 'المنارة', en: 'Manara' },
        { ar: 'عين المريسة', en: 'Ain El Mreisseh' },
        { ar: 'كليمنصو', en: 'Clemenceau' },
        { ar: 'قريطم', en: 'Koraytem' },
        { ar: 'الروشة', en: 'Raouche' },
        { ar: 'الرملة البيضاء', en: 'Ramlet El Baida' },
        { ar: 'الصنائع', en: 'Sanayeh' },
        { ar: 'عائشة بكار', en: 'Aisha Bakkar' },
        { ar: 'المزرعة', en: 'Mazraa' },
        { ar: 'الطريق الجديدة', en: 'Tarik El Jdideh' },
        { ar: 'المصيطبة', en: 'Msaytbeh' },
        { ar: 'برج أبي حيدر', en: 'Burj Abi Haidar' },
        { ar: 'زقاق البلاط', en: 'Zokak El Blat' },
        { ar: 'الباشورة', en: 'Bachoura' },
        { ar: 'رأس النبع', en: 'Ras El Nabaa' },
        { ar: 'وسط بيروت', en: 'Beirut Downtown' },
        { ar: 'الصيفي', en: 'Saifi' },
        { ar: 'الجميزة', en: 'Gemmayzeh' },
        { ar: 'مار مخايل', en: 'Mar Mikhael' },
        { ar: 'الأشرفية', en: 'Achrafieh' },
        { ar: 'بدارو', en: 'Badaro' },
        { ar: 'المتحف', en: 'Museum' },
        { ar: 'الحرش', en: 'Horsh Beirut' },
        { ar: 'الجناح', en: 'Jnah' },
        { ar: 'بئر حسن', en: 'Bir Hassan' },
        { ar: 'الأوزاعي', en: 'Ouzai' },
      ],
    },
    {
      id: 'dahieh',
      ar: 'ضاحية بيروت الجنوبية',
      en: 'Beirut Southern Suburbs',
      areas: [
        { ar: 'الغبيري', en: 'Ghobeiry' },
        { ar: 'الشياح', en: 'Chiyah' },
        { ar: 'حارة حريك', en: 'Haret Hreik' },
        { ar: 'برج البراجنة', en: 'Burj El Barajneh' },
        { ar: 'المريجة', en: 'Mreijeh' },
        { ar: 'الليلكي', en: 'Laylaki' },
        { ar: 'حي السلم', en: 'Hay El Selloum' },
        { ar: 'الرويس', en: 'Rouais' },
        { ar: 'بئر العبد', en: 'Bir El Abed' },
        { ar: 'الكفاءات', en: 'Kafaat' },
        { ar: 'المعمورة', en: 'Maamoura' },
        { ar: 'تحويطة الغدير', en: 'Tahwitat El Ghadir' },
      ],
    },
    {
      id: 'baabda',
      ar: 'بعبدا',
      en: 'Baabda',
      areas: [
        { ar: 'بعبدا', en: 'Baabda' },
        { ar: 'الحازمية', en: 'Hazmieh' },
        { ar: 'الحدث', en: 'Hadath' },
        { ar: 'فرن الشباك', en: 'Furn El Chebbak' },
        { ar: 'عين الرمانة', en: 'Ain El Remmaneh' },
        { ar: 'الشويفات', en: 'Choueifat' },
        { ar: 'كفرشيما', en: 'Kfarshima' },
        { ar: 'بسابا', en: 'Bsaba' },
        { ar: 'يرزة', en: 'Yarze' },
        { ar: 'الجمهور', en: 'Jamhour' },
        { ar: 'عاريا', en: 'Aaraya' },
      ],
    },
    {
      id: 'metn',
      ar: 'المتن',
      en: 'Metn',
      areas: [
        { ar: 'برج حمود', en: 'Bourj Hammoud' },
        { ar: 'سن الفيل', en: 'Sin El Fil' },
        { ar: 'الدكوانة', en: 'Dekwaneh' },
        { ar: 'المكلس', en: 'Mkalles' },
        { ar: 'جديدة المتن', en: 'Jdeideh' },
        { ar: 'الزلقا', en: 'Zalka' },
        { ar: 'جل الديب', en: 'Jal El Dib' },
        { ar: 'أنطلياس', en: 'Antelias' },
        { ar: 'النقاش', en: 'Naccache' },
        { ar: 'ضبية', en: 'Dbayeh' },
        { ar: 'الرابية', en: 'Rabieh' },
        { ar: 'الفنار', en: 'Fanar' },
        { ar: 'المنصورية', en: 'Mansourieh' },
        { ar: 'بيت مري', en: 'Beit Mery' },
        { ar: 'برمانا', en: 'Broummana' },
        { ar: 'بكفيا', en: 'Bikfaya' },
        { ar: 'ضهور الشوير', en: 'Dhour El Choueir' },
      ],
    },
    {
      id: 'keserwan',
      ar: 'كسروان',
      en: 'Keserwan',
      areas: [
        { ar: 'جونيه', en: 'Jounieh' },
        { ar: 'الكسليك', en: 'Kaslik' },
        { ar: 'صربا', en: 'Sarba' },
        { ar: 'ذوق مصبح', en: 'Zouk Mosbeh' },
        { ar: 'ذوق مكايل', en: 'Zouk Mikael' },
        { ar: 'عدما', en: 'Adma' },
        { ar: 'حريصا', en: 'Harissa' },
        { ar: 'غزير', en: 'Ghazir' },
        { ar: 'كفرحباب', en: 'Kfarhbab' },
        { ar: 'بلونة', en: 'Ballouneh' },
        { ar: 'عجلتون', en: 'Ajaltoun' },
        { ar: 'فاريا', en: 'Faraya' },
        { ar: 'فقرا', en: 'Faqra' },
      ],
    },
    {
      id: 'jbeil',
      ar: 'جبيل',
      en: 'Jbeil (Byblos)',
      areas: [
        { ar: 'جبيل', en: 'Byblos' },
        { ar: 'عمشيت', en: 'Amchit' },
        { ar: 'حالات', en: 'Halat' },
        { ar: 'البوار', en: 'Bouar' },
        { ar: 'جدايل', en: 'Jeddayel' },
        { ar: 'عنايا', en: 'Annaya' },
        { ar: 'قرطبا', en: 'Qartaba' },
        { ar: 'لحفد', en: 'Laqlouq' },
      ],
    },
    {
      id: 'aley',
      ar: 'عاليه',
      en: 'Aley',
      areas: [
        { ar: 'عاليه', en: 'Aley' },
        { ar: 'بشامون', en: 'Bchamoun' },
        { ar: 'عرمون', en: 'Aramoun' },
        { ar: 'خلدة', en: 'Khalde' },
        { ar: 'سوق الغرب', en: 'Souk El Gharb' },
        { ar: 'شملان', en: 'Chemlan' },
        { ar: 'بحمدون', en: 'Bhamdoun' },
        { ar: 'صوفر', en: 'Sofar' },
        { ar: 'كحالة', en: 'Kahale' },
        { ar: 'عيناب', en: 'Ainab' },
      ],
    },
    {
      id: 'chouf',
      ar: 'الشوف',
      en: 'Chouf',
      areas: [
        { ar: 'الدامور', en: 'Damour' },
        { ar: 'الناعمة', en: 'Naameh' },
        { ar: 'برجا', en: 'Barja' },
        { ar: 'الجية', en: 'Jiyeh' },
        { ar: 'شحيم', en: 'Chhim' },
        { ar: 'بعقلين', en: 'Baakline' },
        { ar: 'دير القمر', en: 'Deir El Qamar' },
        { ar: 'بيت الدين', en: 'Beiteddine' },
        { ar: 'المختارة', en: 'Mokhtara' },
        { ar: 'عين زحلتا', en: 'Ain Zhalta' },
        { ar: 'كفرحيم', en: 'Kfarhim' },
      ],
    },
    {
      id: 'saida',
      ar: 'صيدا',
      en: 'Saida (Sidon)',
      areas: [
        { ar: 'صيدا المدينة', en: 'Saida City' },
        { ar: 'حارة صيدا', en: 'Haret Saida' },
        { ar: 'عبرا', en: 'Abra' },
        { ar: 'الهلالية', en: 'Hlaliyeh' },
        { ar: 'مجدليون', en: 'Majdelyoun' },
        { ar: 'درب السيم', en: 'Darb El Sim' },
        { ar: 'الغازية', en: 'Ghazieh' },
        { ar: 'عين الحلوة', en: 'Ain El Helweh' },
      ],
    },
    {
      id: 'tyre',
      ar: 'صور',
      en: 'Tyre',
      areas: [
        { ar: 'صور المدينة', en: 'Tyre City' },
        { ar: 'البص', en: 'El Buss' },
        { ar: 'العباسية', en: 'Abbassieh' },
        { ar: 'برج الشمالي', en: 'Burj El Shamali' },
        { ar: 'معركة', en: 'Maaraka' },
        { ar: 'قانا', en: 'Qana' },
        { ar: 'جويا', en: 'Jwaya' },
        { ar: 'القليلة', en: 'Qlaileh' },
      ],
    },
    {
      id: 'nabatieh',
      ar: 'النبطية',
      en: 'Nabatieh',
      areas: [
        { ar: 'النبطية التحتا', en: 'Nabatieh El Tahta' },
        { ar: 'النبطية الفوقا', en: 'Nabatieh El Faouqa' },
        { ar: 'كفررمان', en: 'Kfarroummane' },
        { ar: 'حبوش', en: 'Habboush' },
        { ar: 'زبدين', en: 'Zebdine' },
        { ar: 'دير الزهراني', en: 'Deir El Zahrani' },
        { ar: 'أرنون', en: 'Arnoun' },
      ],
    },
    {
      id: 'bintjbeil',
      ar: 'بنت جبيل',
      en: 'Bint Jbeil',
      areas: [
        { ar: 'بنت جبيل', en: 'Bint Jbeil' },
        { ar: 'تبنين', en: 'Tebnine' },
        { ar: 'عيترون', en: 'Aitaroun' },
        { ar: 'عين إبل', en: 'Ain Ebel' },
        { ar: 'رميش', en: 'Rmeish' },
      ],
    },
    {
      id: 'marjeyoun',
      ar: 'مرجعيون وحاصبيا',
      en: 'Marjeyoun & Hasbaya',
      areas: [
        { ar: 'مرجعيون', en: 'Marjeyoun' },
        { ar: 'الخيام', en: 'Khiam' },
        { ar: 'كفركلا', en: 'Kfarkela' },
        { ar: 'ابل السقي', en: 'Ebel El Saqi' },
        { ar: 'حاصبيا', en: 'Hasbaya' },
        { ar: 'راشيا الفخار', en: 'Rachaya El Foukhar' },
      ],
    },
    {
      id: 'jezzine',
      ar: 'جزين',
      en: 'Jezzine',
      areas: [
        { ar: 'جزين', en: 'Jezzine' },
        { ar: 'بكاسين', en: 'Bkassine' },
        { ar: 'كفرحونة', en: 'Kfarhouna' },
        { ar: 'الريحان', en: 'Rihane' },
      ],
    },
    {
      id: 'tripoli',
      ar: 'طرابلس',
      en: 'Tripoli',
      areas: [
        { ar: 'التل', en: 'El Tall' },
        { ar: 'الميناء', en: 'El Mina' },
        { ar: 'أبو سمرا', en: 'Abou Samra' },
        { ar: 'الزاهرية', en: 'Zahriyeh' },
        { ar: 'القبة', en: 'Qobbeh' },
        { ar: 'باب التبانة', en: 'Bab El Tabbaneh' },
        { ar: 'جبل محسن', en: 'Jabal Mohsen' },
        { ar: 'البداوي', en: 'Beddawi' },
        { ar: 'المنكوبين', en: 'Mankoubin' },
      ],
    },
    {
      id: 'koura',
      ar: 'الكورة',
      en: 'Koura',
      areas: [
        { ar: 'أميون', en: 'Amioun' },
        { ar: 'أنفة', en: 'Enfeh' },
        { ar: 'كفرعقا', en: 'Kfaraakka' },
        { ar: 'بترومين', en: 'Btouratij' },
        { ar: 'دده', en: 'Dedde' },
        { ar: 'بشمزين', en: 'Bechmezzine' },
      ],
    },
    {
      id: 'batroun',
      ar: 'البترون',
      en: 'Batroun',
      areas: [
        { ar: 'البترون', en: 'Batroun' },
        { ar: 'شكا', en: 'Chekka' },
        { ar: 'كفيفان', en: 'Kfifan' },
        { ar: 'تنورين', en: 'Tannourine' },
        { ar: 'دوما', en: 'Douma' },
      ],
    },
    {
      id: 'zgharta',
      ar: 'زغرتا',
      en: 'Zgharta',
      areas: [
        { ar: 'زغرتا', en: 'Zgharta' },
        { ar: 'إهدن', en: 'Ehden' },
        { ar: 'مجدليا', en: 'Majdalaya' },
        { ar: 'أرده', en: 'Ardeh' },
      ],
    },
    {
      id: 'bcharre',
      ar: 'بشري',
      en: 'Bcharre',
      areas: [
        { ar: 'بشري', en: 'Bcharre' },
        { ar: 'الأرز', en: 'The Cedars' },
        { ar: 'حصرون', en: 'Hasroun' },
        { ar: 'بقاعكفرا', en: 'Bqaakafra' },
      ],
    },
    {
      id: 'minieh',
      ar: 'المنية والضنية',
      en: 'Minieh–Dennieh',
      areas: [
        { ar: 'المنية', en: 'Minieh' },
        { ar: 'سير الضنية', en: 'Sir El Dennieh' },
        { ar: 'بقاعصفرين', en: 'Bqaasafrine' },
        { ar: 'حلبا الضنية', en: 'Dennieh' },
      ],
    },
    {
      id: 'akkar',
      ar: 'عكار',
      en: 'Akkar',
      areas: [
        { ar: 'حلبا', en: 'Halba' },
        { ar: 'ببنين', en: 'Bebnine' },
        { ar: 'العبدة', en: 'Abdeh' },
        { ar: 'القبيات', en: 'Qoubaiyat' },
        { ar: 'مشمش', en: 'Machmouch' },
        { ar: 'الشيخ محمد', en: 'Cheikh Mohammad' },
      ],
    },
    {
      id: 'zahle',
      ar: 'زحلة',
      en: 'Zahle',
      areas: [
        { ar: 'زحلة المدينة', en: 'Zahle City' },
        { ar: 'شتورة', en: 'Chtaura' },
        { ar: 'تعنايل', en: 'Taanayel' },
        { ar: 'قب الياس', en: 'Qab Elias' },
        { ar: 'بر الياس', en: 'Bar Elias' },
        { ar: 'رياق', en: 'Rayak' },
        { ar: 'الكرك', en: 'Karak' },
        { ar: 'حوش الأمراء', en: 'Hoch El Oumara' },
      ],
    },
    {
      id: 'westbekaa',
      ar: 'البقاع الغربي',
      en: 'West Bekaa',
      areas: [
        { ar: 'جب جنين', en: 'Jib Jenine' },
        { ar: 'سحمر', en: 'Sohmor' },
        { ar: 'مشغرة', en: 'Machghara' },
        { ar: 'كامد اللوز', en: 'Kamed El Loz' },
        { ar: 'القرعون', en: 'Qaraoun' },
        { ar: 'عيتنيت', en: 'Aitanit' },
      ],
    },
    {
      id: 'rachaya',
      ar: 'راشيا',
      en: 'Rachaya',
      areas: [
        { ar: 'راشيا الوادي', en: 'Rachaya El Wadi' },
        { ar: 'كفرقوق', en: 'Kfarqouq' },
        { ar: 'عيتا الفخار', en: 'Aiha' },
        { ar: 'دير العشاير', en: 'Deir El Achayer' },
      ],
    },
    {
      id: 'baalbek',
      ar: 'بعلبك',
      en: 'Baalbek',
      areas: [
        { ar: 'بعلبك المدينة', en: 'Baalbek City' },
        { ar: 'دورس', en: 'Douris' },
        { ar: 'اللبوة', en: 'Laboueh' },
        { ar: 'شمسطار', en: 'Chmistar' },
        { ar: 'بريتال', en: 'Brital' },
        { ar: 'عرسال', en: 'Arsal' },
        { ar: 'رأس بعلبك', en: 'Ras Baalbek' },
      ],
    },
    {
      id: 'hermel',
      ar: 'الهرمل',
      en: 'Hermel',
      areas: [
        { ar: 'الهرمل', en: 'Hermel' },
        { ar: 'القصر', en: 'Qasr' },
        { ar: 'الشواغير', en: 'Chawaghir' },
      ],
    },
  ],
};
