// ═══════════════════════════════════════════════════════════
//  Diamond Perfume — Demo Products
//  منتجات نموذجية فاخرة — استبدلها بمنتجاتك الحقيقية
// ═══════════════════════════════════════════════════════════

export const CATEGORIES = [
  {
    id: 'women',
    ar: 'عطور نسائية',
    en: 'For Her',
    descAr: 'أنوثة تُروى كحكاية عطرية',
    descEn: 'Femininity told as a fragrant tale',
    image: '/images/rose-verdun.jpg',
  },
  {
    id: 'men',
    ar: 'عطور رجالية',
    en: 'For Him',
    descAr: 'حضورٌ لا يُنسى',
    descEn: 'A presence never forgotten',
    image: '/images/diamond-noir.jpg',
  },
  {
    id: 'oriental',
    ar: 'عود وشرقيات',
    en: 'Oud & Oriental',
    descAr: 'أصالة الشرق بلمسة ملكية',
    descEn: 'Eastern heritage with a royal touch',
    image: '/images/royal-oud.jpg',
  },
  {
    id: 'niche',
    ar: 'نيش وفاخرة',
    en: 'Niche & Exclusive',
    descAr: 'توقيع عطري لا يتكرر',
    descEn: 'A scent signature like no other',
    image: '/images/sapphire-nuit.jpg',
  },
]

export const PRODUCTS = [
  {
    id: 'royal-oud',
    cat: 'oriental',
    gender: { ar: 'للجنسين', en: 'Unisex' },
    nameAr: 'عود رويال',
    nameEn: 'Royal Oud',
    notesAr: 'عود هندي، زعفران، عنبر رمادي',
    notesEn: 'Indian oud, saffron, grey amber',
    descAr: 'افتتاحية من الزعفران الذهبي تذوب في قلب من العود الهندي الفاخر، لتستقر على عنبرٍ دافئ يرافقك طوال اليوم.',
    descEn: 'A golden saffron opening melting into precious Indian oud, resting on warm amber that lasts all day.',
    size: '100 ml',
    price: 65,
    oldPrice: null,
    bestSeller: true,
    rating: 4.9,
    image: '/images/royal-oud.jpg',
  },
  {
    id: 'diamond-noir',
    cat: 'men',
    gender: { ar: 'رجالي', en: 'For Him' },
    nameAr: 'دياموند نوار',
    nameEn: 'Diamond Noir',
    notesAr: 'برغموت، جلد، فيتيفر مدخّن',
    notesEn: 'Bergamot, leather, smoked vetiver',
    descAr: 'عطر الليل والحضور الطاغي؛ برغموت حاد يعانق الجلد الفاخر ودخان الفيتيفر الغامض.',
    descEn: 'The scent of night and command; sharp bergamot embracing fine leather and mysterious smoked vetiver.',
    size: '100 ml',
    price: 55,
    oldPrice: null,
    bestSeller: true,
    rating: 4.8,
    image: '/images/diamond-noir.jpg',
  },
  {
    id: 'rose-verdun',
    cat: 'women',
    gender: { ar: 'نسائي', en: 'For Her' },
    nameAr: 'روز فردان',
    nameEn: 'Rose Verdun',
    notesAr: 'ورد دمشقي، فانيليا، مسك أبيض',
    notesEn: 'Damask rose, vanilla, white musk',
    descAr: 'وردة دمشقية قطفت عند الفجر، تتوسطها حلاوة الفانيليا ونقاء المسك الأبيض.',
    descEn: 'A Damask rose picked at dawn, wrapped in vanilla sweetness and pure white musk.',
    size: '100 ml',
    price: 48,
    oldPrice: null,
    bestSeller: true,
    rating: 4.9,
    image: '/images/rose-verdun.jpg',
  },
  {
    id: 'sultan-amber',
    cat: 'oriental',
    gender: { ar: 'للجنسين', en: 'Unisex' },
    nameAr: 'عنبر سلطان',
    nameEn: 'Sultan Amber',
    notesAr: 'عنبر، باتشولي، خشب الصندل',
    notesEn: 'Amber, patchouli, sandalwood',
    descAr: 'تركيبة سلطانية دافئة تجمع العنبر الملكي مع عمق الباتشولي ونعومة الصندل.',
    descEn: 'A warm royal composition of amber, deep patchouli and silky sandalwood.',
    size: '100 ml',
    price: 58,
    oldPrice: 72,
    bestSeller: false,
    rating: 4.7,
    image: '/images/sultan-amber.jpg',
  },
  {
    id: 'pure-musk',
    cat: 'oriental',
    gender: { ar: 'للجنسين', en: 'Unisex' },
    nameAr: 'مسك الطهارة',
    nameEn: 'Pure Musk',
    notesAr: 'مسك أبيض، زهر القطن، ياسمين',
    notesEn: 'White musk, cotton flower, jasmine',
    descAr: 'نقاء الطهارة في زجاجة؛ مسك أبيض ناعم يعانق زهرة القطن ولمسة ياسمين.',
    descEn: 'Purity in a bottle; soft white musk embracing cotton flower with a touch of jasmine.',
    size: '50 ml',
    price: 22,
    oldPrice: null,
    bestSeller: false,
    rating: 4.8,
    image: '/images/pure-musk.jpg',
  },
  {
    id: 'sapphire-nuit',
    cat: 'niche',
    gender: { ar: 'رجالي', en: 'For Him' },
    nameAr: 'سفير الليل',
    nameEn: 'Sapphire Nuit',
    notesAr: 'لافندر، حبوب التونكا، خشب الأرز',
    notesEn: 'Lavender, tonka bean, cedarwood',
    descAr: 'ليلٌ أزرق عميق؛ لافندر هادئ يتلألأ فوق تونكا كريمية وقاعدة من أرز الأطلس.',
    descEn: 'A deep blue night; calm lavender sparkling over creamy tonka and Atlas cedar.',
    size: '100 ml',
    price: 74,
    oldPrice: null,
    bestSeller: true,
    rating: 5.0,
    image: '/images/sapphire-nuit.jpg',
  },
  {
    id: 'vanilla-royale',
    cat: 'women',
    gender: { ar: 'نسائي', en: 'For Her' },
    nameAr: 'فانيليا رويال',
    nameEn: 'Vanilla Royale',
    notesAr: 'فانيليا مدغشقر، كراميل، تونكا',
    notesEn: 'Madagascar vanilla, caramel, tonka',
    descAr: 'حلوى ملكية لا تُقاوم؛ فانيليا مدغشقرية كريمية مع خيوط الكراميل الذهبية.',
    descEn: 'An irresistible royal gourmand; creamy Madagascar vanilla laced with golden caramel.',
    size: '100 ml',
    price: 62,
    oldPrice: null,
    bestSeller: true,
    rating: 4.9,
    image: '/images/vanilla-royale.jpg',
  },
  {
    id: 'saffron-leather',
    cat: 'niche',
    gender: { ar: 'للجنسين', en: 'Unisex' },
    nameAr: 'جلد الزعفران',
    nameEn: 'Saffron Leather',
    notesAr: 'زعفران، جلد إيطالي، تبغ',
    notesEn: 'Saffron, Italian leather, tobacco',
    descAr: 'جرأة الزعفران وفخامة الجلد الإيطالي في عناقٍ دافئ مع أوراق التبغ المعتّقة.',
    descEn: 'Bold saffron and luxurious Italian leather warmed by aged tobacco leaves.',
    size: '100 ml',
    price: 88,
    oldPrice: 110,
    bestSeller: false,
    rating: 4.8,
    image: '/images/saffron-leather.jpg',
  },
  {
    id: 'desert-emerald',
    cat: 'niche',
    gender: { ar: 'للجنسين', en: 'Unisex' },
    nameAr: 'زمرّد الصحراء',
    nameEn: 'Desert Emerald',
    notesAr: 'برغموت، هيل، فيتيفر أخضر',
    notesEn: 'Bergamot, cardamom, green vetiver',
    descAr: 'نسيم أخضر يعبر الصحراء؛ هيل منعش وبرغموت مشرق فوق فيتيفر أخضر نابض.',
    descEn: 'A green breeze crossing the desert; fresh cardamom and bright bergamot over vivid vetiver.',
    size: '100 ml',
    price: 79,
    oldPrice: null,
    bestSeller: false,
    rating: 4.7,
    image: '/images/desert-emerald.jpg',
  },
  {
    id: 'cambodian-oud',
    cat: 'oriental',
    gender: { ar: 'للجنسين', en: 'Unisex' },
    nameAr: 'دهن عود كمبودي معتّق',
    nameEn: 'Aged Cambodian Oud Oil',
    notesAr: 'عود كمبودي نقي معتّق ١٢ سنة',
    notesEn: 'Pure 12-year-aged Cambodian oud',
    descAr: 'دهن عود كمبودي نقي معتّق اثنتي عشرة سنة؛ قطرة واحدة تكفي لحضورٍ يسبق اسمك.',
    descEn: 'Pure Cambodian oud oil aged twelve years; one drop precedes your name.',
    size: '12 ml',
    price: 120,
    oldPrice: null,
    bestSeller: true,
    rating: 5.0,
    image: '/images/cambodian-oud.jpg',
  },
  {
    id: 'diamond-bakhoor',
    cat: 'oriental',
    gender: { ar: 'للبيت', en: 'For Home' },
    nameAr: 'بخور الماس الفاخر',
    nameEn: 'Diamond Bakhoor',
    notesAr: 'عود معطر، مسك، خشب الصندل',
    notesEn: 'Scented oud chips, musk, sandalwood',
    descAr: 'بخور فاخر يملأ المجلس بعبق الضيافة العربية الأصيلة.',
    descEn: 'Luxurious bakhoor that fills your majlis with authentic Arabian hospitality.',
    size: '80 g',
    price: 35,
    oldPrice: 45,
    bestSeller: false,
    rating: 4.6,
    image: '/images/diamond-bakhoor.jpg',
  },
  {
    id: 'or-eternel',
    cat: 'women',
    gender: { ar: 'نسائي', en: 'For Her' },
    nameAr: 'أور إتيرنيل',
    nameEn: 'Or Éternel',
    notesAr: 'ياسمين، زهر البرتقال، مسك ذهبي',
    notesEn: 'Jasmine, orange blossom, golden musk',
    descAr: 'ذهبٌ سائل يفيض أنوثة؛ ياسمين ليلي يتشابك مع زهر البرتقال ومسكٍ ذهبي دافئ.',
    descEn: 'Liquid gold overflowing with femininity; night jasmine entwined with orange blossom and warm golden musk.',
    size: '100 ml',
    price: 57,
    oldPrice: null,
    bestSeller: true,
    rating: 4.9,
    image: '/images/or-eternel.jpg',
  },
]

export const CAT_LABEL = {
  women: { ar: 'نسائية', en: 'Women' },
  men: { ar: 'رجالية', en: 'Men' },
  oriental: { ar: 'عود وشرقيات', en: 'Oud & Oriental' },
  niche: { ar: 'نيش', en: 'Niche' },
}
